### PR TITLE
Allow to update title/body and option for labels inheritance

### PR DESCRIPTION
**Pull request by radtriste**
https://github.com/carloscastrojumo/github-cherry-pick-action/issues/9

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Would be useful, will this get reviewed?

**Comment by ricardozanini** [comment]
@carloscastrojumo can you please take a look?

**Comment by carloscastrojumo** [comment]
Sorry for the delay. Merged and released. Thank you for the contribution @radtriste.

**Comment by radtriste** [comment]
@carloscastrojumo Thanks for the merge and the release !

**Pull request merged**
