### PR TITLE
Title and body substitutions

### LINKED ISSUE #13: Allow referencing to the closed/merged PR when creating the new PR
E.g. following from #10, it would be great if it was possible substitute say `{cherry_picked_pr}` with a link to the PR which triggered the action.

### PR DESCRIPTION
**Pull request by samuelcolvin**
fix #13, continued from #10.

So that I can use:

```yaml
      - name: Cherry pick into release-v2.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-v2.0
          title: '[cherry-pick] {old_title}'
          body: 'Cherry picking #{old_pull_request_id} onto this branch'

### CODE REVIEW

**Comment by samuelcolvin** [comment]
#10 forgot to add `title` and `body` to the readme, fixed here.

Please review.

**Comment by samuelcolvin** [comment]
This is working correctly see https://github.com/samuelcolvin/pydantic-sandbox/pull/16.

**Comment by samuelcolvin** [comment]
Hi @carloscastrojumo any chance you could review and perhaps merge this? I'd like to use it on pydantic.

**Review by carloscastrojumo — APPROVED** [review]
LGTM. Thank you for contributing @samuelcolvin

**Pull request merged**
