### PR TITLE
[ISSUE-18] Customize cherry pick branch name

### PR DESCRIPTION
**Pull request by lampajr**
Fix https://github.com/carloscastrojumo/github-cherry-pick-action/issues/18

So that users can have control over the new cherry-pick branch name, like re-using the original branch name concatenaed with the target one:
```yaml
    steps:
      - name: Calculate release branch
        run: |
          label=${{ matrix.name }}
          echo "RELEASE_BRANCH=release/v1" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Perform cherry-pick
        uses: lampajr/github-cherry-pick-action@issue-18_cp_branch_name
        with:
          branch: "${{ env.RELEASE_BRANCH }}"
          title: "[${{ env.RELEASE_BRANCH }}] ${{ github.event.pull_request.title }}"
          body: "cherry-pick: ${{ github.event.pull_request.html_url }}"
          inherit_labels: false
          reviewers: |
            ${{ github.event.pull_request.user.login }}
          cherry-pick-branch: "${{ github.event.pull_request.head.ref }}_${{ env.RELEASE_BRANCH }}"
```

In this way users can cherry-pick the same change on more than one release branch or simply using their branching convention. 

> **Note:** In addition I also added some simple mocked tests that I used to validate the fix itself, I would include them too but if you don't agree I can remove them as well.

### CODE REVIEW

**Comment by lampajr** [comment]
I tried this fix in a custom repo.

Workflow config: https://github.com/lampajr/chain-status-example/blob/main/.github/workflows/backport.yaml

Generated cherry pick PRs:
- Using default branch name: https://github.com/lampajr/chain-status-example/pull/4
- Customizing cherry pick branch name: https://github.com/lampajr/chain-status-example/pull/6

**Comment by lampajr** [comment]
Hi @carloscastrojumo whenever you get time could you please code review this?

**Comment by carloscastrojumo** [comment]
Hi @lampajr . Thank you for your contribution, specially for the new suite of tests. 

I'm ok with override the cherry-pick branch name, I'm just curious, and this is more related to the actual #18, in what scenarios is this an issue? Release branch + git commit SHA should always be unique or what am I missing?

**Review by carloscastrojumo — APPROVED** [review]

**Comment by lampajr** [comment]
Hi @carloscastrojumo , you are right that's not an issue as I completely missed the `inputs.branch` in the `prBranch` creation, my bad sorry.

On the other hand, just to give you more context on why I need this change: we are actually using [build-chain](https://github.com/kiegroup/github-action-build-chain) to perform cross-repositories projects builds - this tool relies on the branch name in order to cross check multiple PRs on different repos, therefore we must ensure that multiple PRs (__on different repos__, that's the crucial point) share the same branch name (which cannot be ensured if using commit sha as part of the branch name itself).

If you want I can create a new issue with this motivation and link it to this PR, wdyt?

**Comment by carloscastrojumo** [comment]
It's fine. I will question the issue owner to see how can I help. 

Thanks again for contributing.

**Comment by lampajr** [comment]
Thank you very much @carloscastrojumo

**Pull request merged**
